apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-product-score-server
  name: stage-product-score-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage-product-score-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stage-product-score-server
    spec:
      containers:
        - image: gcr.io/taf-mvp-1/product-score@sha256:0e6db7b9ca3995e0ba43ba299c6e70365f01638cd892a6a24f6b19c4bae9d8eb
          name: stage-product-score-server
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: stage-product-score-secret
            - configMapRef:
                name: stage-product-score-config
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/
              port: 8080
              scheme: HTTP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: stage-product-score-server
  name: stage-product-score-server
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
  selector:
    app: stage-product-score-server
  type: NodePort